### ISSUE TITLE
イベントデータをイベント構造体に格納する．

### ISSUE THREAD

**Issue by hikacchi64** [yama2662/Law_of_the_jungle#1]
## やること
* テキストファイルにイベントデータを用意する
* テキストファイルのイベントデータをイベント構造体に格納する

## 進捗
* テスト用のイベントデータを用意した
* 格納するプログラムを作成
* 確認表示の部分でバグっている

**Comment by yama2662** [comment]
@hikacchi64 
こっちの環境でコンパイル＆実行してみたけど、EncodingのWarning以外は問題なし（多分……）
表示の部分も特に問題なく実行できた

import_event_data.cがShift JISで書かれているようなので、utf-8にしておいてくれると助かります

**Comment by yama2662** [comment]
とりあえずマージしたので閉じます．
